loginApp/urls.py
from django.urls import  path
from . import views

urlpatterns=[

    path('',views.index, name='index'),

    path('create/',views.store,name='store'),
    path('usuario/edit/<int:id>/', views.update, name='update'),
    path('usuario/delete/<int:id>/',views.deleteView,name='delete'),
    path('listar/',views.listar,name="listar"),
    path('login/',views.login,name="login")
]

webApp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('loginApp.urls','loginApp'),namespace='loginApp')),

]

loginApp/models.py
from django.db import models


class Usuario(models.Model):
    #unique=True
    nome=models.CharField(max_length=80)
    sobrenome=models.CharField(max_length=20)
    senha=models.CharField(max_length=8)

loginApp/forms.py
from django import forms
from .models import Usuario


class PostForm(forms.ModelForm):


      class Meta:
            # Modelo base
            model = Usuario

            fields = (
                  'nome',
                  'sobrenome',
                  'senha',

            )

class LoginForm(forms.ModelForm):
      class Meta:
            model=Usuario
            fields=(
                  'nome',
                  'senha'
            )

loginApp/views.py
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm,LoginForm
from .models import Usuario


def index(request):
    return render(request, 'loginApp/base.html')

def login(request):
    form =LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            nome_form = form.cleaned_data['nome']
            senha_form = form.cleaned_data['senha']
            teste=Usuario.objects.filter(nome=nome_form,senha=senha_form).first()
            if(teste !=None):
                return render(request, 'loginApp/BemVindo.html', { 'usuario': teste})
            else:
                form = LoginForm()
                return render(request, 'loginApp/login.html', {'sucess': 1, 'form': form})

    elif request.method == 'GET':
        return render(request, 'loginApp/login.html', {'form': form, 'sucess': 0})



def store(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            nome_form = form.cleaned_data['nome']
            sobrenome_form = form.cleaned_data['sobrenome']
            senha_form = form.cleaned_data['senha']

            usuario = Usuario(nome=nome_form, sobrenome=sobrenome_form, senha=senha_form)
            usuario.save()
            form = PostForm()
            return render(request,'loginApp/create.html',{'sucess': 1,'form': form})
    elif request.method == 'GET':
        return render(request, 'loginApp/create.html', {'form': form,'sucess': 0})


def listar(request):
    return render(request, 'loginApp/listar.html', {'usuarios': Usuario.objects.all(),})

def update(request, id):
    usuario = get_object_or_404(Usuario, pk=id)
    form = PostForm(instance=usuario)
    if request.method == 'POST':
        form =PostForm(request.POST,instance=usuario)

        if form.is_valid():
            user = form.save(commit=False)
            user.nome = form.cleaned_data['nome']
            user.sobrenome = form.cleaned_data['sobrenome']
            user.senha = form.cleaned_data['senha']
            user.save()
            return redirect('loginApp:listar')
    elif request.method == 'GET':
            form=PostForm(instance=usuario)
            return render(request, 'loginApp/update.html', {'form': form,'usuario':usuario})


def deleteView(request, id):

    usuario = Usuario.objects.filter(id=id).first()
    usuario.delete()
    return redirect('loginApp:listar')

loginApp/templates/loginApp/BemVindo.html
{% extends 'loginApp/base.html'  %}
{% block title %}Adicionar um usuário{% endblock %}
 {% block content %}
<br>
<h2><b>Bem Vindo</b>,  {{ usuario.nome}} {{ usuario.sobrenome}}</h2>
{% endblock %}

loginApp/templates/loginApp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 <link href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.min.css" rel="stylesheet">
    <script src="//code.jquery.com/jquery-3.2.1.min.js"></script>
  <script src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
</head>
<body>


<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/create/">Criar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/listar/">Listar</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/login/" >Login</a>
      </li>
    </ul>
  </div>
</nav>

<div  class="container">
 {% block content %}
        {% endblock %}
</div>
<script>
  $(document).ready(function(){
      $('#minhaTabela').DataTable({
        	"language": {
                "lengthMenu": "Mostrando _MENU_ registros por página",
                "zeroRecords": "Nada encontrado",
                "info": "Mostrando página _PAGE_ de _PAGES_",
                "infoEmpty": "Nenhum registro disponível",
                "infoFiltered": "(filtrado de _MAX_ registros no total)"
            }
        });
  });
  </script>

</body>
</html>

loginApp/templates/loginApp/create.html
{% extends 'loginApp/base.html'  %}
{% block title %}Adicionar um usuário{% endblock %}
 {% load bootstrap %}


{% block content %}
{% if sucess %}
<br>
<div class="alert alert-primary" role="alert">
  Cadastrado Com Sucesso!!!
</div>
{% endif%}
<div>
    <p class="h1">Cadastrar</p>
<form action="." method="POST" class="post-form">
       {% csrf_token %}
      {{  form|bootstrap }}
  <button type="submit" id="btn" class="btn btn-primary">Enviar</button>

</form>
    </div>
{% endblock %}

loginApp/templates/loginApp/index.html
{% extends 'loginApp/base.html'  %}
{% block title %}Home{% endblock %}

{% block content %}
<span>Bem Vindo</span>
{% endblock %}

loginApp/templates/loginApp/listar.html
 {% extends 'loginApp/base.html'  %}
{% block title %}Listar os usuários{% endblock %}
 {% block content %}

 <table id="minhaTabela"  style="margin-top:150px;" class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nome</th>
      <th scope="col">Sobrenome</th>
      <th scope="col">Senha</th>
         <th scope="col">Ações</th>
    </tr>
  </thead>
  <tbody>
  {% for usuario in usuarios %}
    <tr>
       <th scope="row">{{usuario.id}}</th>
      <td>{{usuario.nome}}</td>
      <td>{{usuario.sobrenome}}</td>
      <td>{{usuario.senha}}</td>
        <td>
            <a href="{% url 'loginApp:update' id=usuario.id %}"
 class="btn btn-info">
     <svg width="1em" height="1em" style="color:orange;" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
</svg>
        </a>
            <a href="{% url 'loginApp:delete' id=usuario.id %}"
 class="btn btn-outline-danger">
          <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
</svg>
        </a>
        </td>
    </tr>
{% endfor %}

  </tbody>
</table>
     </div>
{% endblock %}

loginApp/templates/loginApp/login.html
{% extends 'loginApp/base.html'  %}
{% block title %}Login{% endblock %}
 {% load bootstrap %}


{% block content %}
{% if sucess%}
<br>
<div class="alert alert-primary" role="alert">
  Nome ou Senha incorretos
</div>
{% endif%}
<div>
    <p class="h1">Login</p>
<form action="." method="POST" class="post-form">
       {% csrf_token %}
      {{  form|bootstrap }}
  <button type="submit" id="btn" class="btn btn-primary">Login</button>

</form>
    </div>
{% endblock %}

loginApp/templates/loginApp/sucess.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

loginApp/templates/loginApp/update.html
{% extends 'loginApp/base.html'  %}
{% block title %}Editar um usuário{% endblock %}
 {% load bootstrap %}


{% block content %}

<div>
    <p class="h1">Cadastrar</p>
<form action="{% url 'loginApp:update' id=usuario.id %}" method="POST" class="post-form">
       {% csrf_token %}
      {{  form|bootstrap }}
  <button type="submit" id="btn" class="btn btn-primary">Enviar</button>

</form>
    </div>
{% endblock %}